### ISSUE TITLE
When I try to use this, I get an error

### ISSUE THREAD

**Issue by bengt-a** [programmer2514/RPi-Google-Drive#2]
When I try to use this, I get an error:
Authorization Key: (censored)
```
gdrivefs 0.14.13 has requirement oauth2client<4.0.0, but you'll have oauth2client 4.1.3 which is incompatible.
Installing collected packages: oauth2client
  Found existing installation: oauth2client 3.0.0
    Uninstalling oauth2client-3.0.0:
      Successfully uninstalled oauth2client-3.0.0
Successfully installed oauth2client-4.1.3
Creating directories...
Authorizing Google Drive...
Please follow the instructions to sign in to your Google Drive account:
To authorize FUSE to use your Google Drive account, visit the following URL to produce an authorization code:
<skipped>
Authorizing...
WARNING: This subcommand is obsolete. Use the auth_get_url, auth_write, and auth_automatic subcommands.

Authorization code recorded.
Mounting drive files...
Traceback (most recent call last):
  File "/usr/local/bin/gdfs", line 76, in <module>
    _main()
  File "/usr/local/bin/gdfs", line 73, in _main
    option_string=option_string)
  File "/usr/local/lib/python3.7/dist-packages/gdrivefs/gdfuse.py", line 858, in mount
    raise Exception("Google does not like oauth2client >=4.0.0 .")
Exception: Google does not like oauth2client >=4.0.0 .
Listing files...
_______________________________
Is this correct (Y/n)?

```

**Comment by programmer2514** [comment]
Hmmm...I've never seen this particular error before. Did you make sure to paste the authorization code from the link in the terminal? You can also try downgrading oauth2client to an older version (<4.0.0). I'm actually on vacation ATM, so sorry I can't be of more help.

I'll try to update this script to stop using obsolete software when I get home.

**Comment by bengt-a** [comment]
I have tried uninstalling oauth2client and rerunning your installation script, but the result is always the same. It first installs version 3.something, then uninstalls it and installs 4.1.3. I have tried to understand how the script works to figure out how to solve it myself (i.e. to not get the 4.1.3 version) but I didn't figure it out.

Enjoy your vacation. Perhaps you get time to look at it when you get back :)

**Comment by programmer2514** [comment]
Okay, I've uploaded a new release - let me know what you think.
I reworked the entire thing - new methods, better usability, etc. It should also be a LOT more stable now.
I also commented this version, so it should be much easier to understand how it works (I'm _still_ not entirely sure how it ever worked before, but I can definitely say it works much better now).

Edit: Just in case you were wondering, the problematic line was `sudo pip3 install oauth2client -U`. The `-U` parameter was force-updating the oauth2client package to version 4.1.3. To fix it, I simply removed that line altogether as installing gdrivefs automatically installs oauth2client version 3.0.0.

**Comment by bengt-a** [comment]
I thought you were on vacation? :D Thank you so much for spending your time to help me!

Oh, I just ran the script (from the ssh remote shell on my pi). It says something about a web browser window will open... :D But I am using a headless Pi without any graphic interface...

**Comment by bengt-a** [comment]
```

Authorizing Google Drive...
A new browser window will open shortly
Please sign in to your Google account to authorize GDFS
After authorization is complete, close the browser window to continue
```




Here I pressed ^C to continue since there will never be a web browser page...
I thought it might work since I already authorized GFDS with the earlier script


```
Traceback (most recent call last):
  File "/usr/local/bin/gdfstool", line 196, in <module>
    main()
  File "/usr/local/bin/gdfstool", line 175, in main
    _handle_auth_automatic(args)
  File "/usr/local/bin/gdfstool", line 66, in _handle_auth_automatic
    aa.get_and_write_creds()
  File "/usr/local/lib/python3.7/dist-packages/gdrivefs/auto_auth.py", line 245, in get_and_write_creds
    time.sleep(1)
KeyboardInterrupt
Creating folders...
Modifying permissions...
Mounting drive files...
Traceback (most recent call last):
  File "/usr/local/bin/gdfs", line 76, in <module>
    _main()
  File "/usr/local/bin/gdfs", line 73, in _main
    option_string=option_string)
  File "/usr/local/lib/python3.7/dist-packages/gdrivefs/gdfuse.py", line 852, in mount
    (auth_storage_filepath,))
ValueError: Credential path is not valid: [/home/pi/.gdfs/creds]
Listing files...
_______________________________
Is this correct (Y/n)?
```

**Comment by bengt-a** [comment]
BUT! If I removed the -U in the OLD script, it worked!!!

**Comment by programmer2514** [comment]
I just got back from vacation yesterday. I should be able to get a headless version of the new script uploaded soon, but I wouldn't really recommend using the old one - pretty much everything it does is deprecated, especially its handling of the rc.local file (it might break other autostart apps if anything fails).

**Comment by programmer2514** [comment]
I've uploaded a new version of the script - the headless version should work well for you :)
Just make sure to follow the instructions under the release notice (Although AFAIK, it shouldn't really matter, it's just to be on the safe side)

**Comment by bengt-a** [comment]
Hi,
I ran all the uninstallers, then the new headless script, and it worked flawlessly!
So much easier than any other solutions I have seen. Simply amazing. You have saved my summer. 🥇 
Great work!!!

**Comment by programmer2514** [comment]
I'm glad I could help! If there's anything else you need, feel free to let me know :)
