### ISSUE TITLE
Selections error out (1,2,3....)

### ISSUE THREAD

**Issue by HawkCollective2890** [programmer2514/RPi-Google-Drive#3]
First off thank you!
I did a manual install using the steps listed in your .sh file. Later I removed the user selection and ran the script (#1 only ) and it completed the process with out errors. ( other than a PIP as root error) 
the issue:
When I would use the automated system, I would select 1, the terminal would toss back errors that correspond with all the if (( $number == lines. 

I am using a Pi3 B+ with 32bit Bullseye.

**Comment by programmer2514** [comment]
If you could provide me with a screenshot or pastebin of the output log, that would be extremely helpful, but the information you've provided is not enough by itself for me to find the issue.
