### ISSUE TITLE
No write permissions. 

### ISSUE THREAD

**Issue by HawkCollective2890** [programmer2514/RPi-Google-Drive#5]
I am scared to bork my Google drive so I am asking for guidance. 
I can create folders.
If i copy items via the GUI. I get "filename": Error opening file “/home/pi/Google Drive/new Pi/LICENSE”: Input/output error
and "the file operation was completed with errors."

if I sudo cp i get "cp: failed to access '/home/pi/Google Drive/new Pi/': Permission denied"
if I cp i get "cp: cannot create regular file '/home/pi/Google Drive/new Pi/installGoogleDrive2.sh': Input/output error"

the files show up on my other computer but with file sizes of zero.

**Comment by programmer2514** [comment]
I unfortunately cannot fix this, as it is a known internal issue with the backend that my tool uses, [gdrivefs](https://github.com/dsoprea/GDriveFS/issues/216).
I apologize for the inconvenience.
